language: go
go:
  - 1.13.7
env: "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mattn/gom
script:
  - go vet -x ./...
  # Install dependencies via gom
  - $HOME/gopath/bin/gom -production install

  # Build linux/amd64 archive
  - export GOOS="linux"
  - export GOARCH="amd64"
  - gom build -v -tags "forceposix" -o build/linux-x64/cli-kintone
  - zip linux-x64.zip build/linux-x64/cli-kintone

  # Build darwin/amd64 archive
  - export GOOS="darwin"
  - export GOARCH="amd64"
  - gom build -v -tags "forceposix" -o build/macos-x64/cli-kintone
  - zip macos-x64.zip build/macos-x64/cli-kintone

  # Build windows/amd64 archive
  - export GOOS="windows"
  - export GOARCH="amd64"
  - gom build -v -tags "forceposix" -o build/windows-x64/cli-kintone.exe
  - zip windows-x64.zip build/windows-x64/cli-kintone.exe

deploy:
  provider: releases
  api_key: 
    secure: "fIWjn/6Zch58EMlj9n0F1QAyvcgsKcG2/iqDzunQ4hERL8NhHJXMunr5nX73Aee5wdxVucL6TrDOVJuZBgtdrI1Yvmjl2SyE1xX6Kubn2fMCHmwEjW13KYXmLiYNlUAmZ3DqqZZZHXNVemYDF2NduBVI3wr/3lYfcxT8ergmqorC1V2TX06PvEOLJjIHgtR+P23X0J0QlzDnL9yTubA6bVJ+JfH93JwjP2gtSQ0jcZ95daLxmo85EszuX2hl9t255iKGQlKcMoGBhjLyM35Gm6lImE+lugC11Y3jM8JOwqfevekGSrnudvXRCQpGx53K9hIgCabMzrz86ozqWfZS6cIrDa+3QRjrT1UgKfHY1p0sklSGkdFHVm0lPhZMp+9pMSiRZTKhOBOypXVtkvD+6avz9snEXgIhYg9nsfiOblTWIl89ke3Te44p3yS4h5Uv2aPJVKNpPbaE2hCo4GsIiLaEK0gupw1UkICEDbvVdi77hZwnV8PrqPmxdUXKIg1avTvjWTPe2z1xLIU0+NYWOCJjMb5qXWAHeqibHmGdULPRNT4Ulwm1yO1mnqhnzWLRa9vTPDhNVjRUIGwHBS1FC0QBaop7X8N45UzxssyQZnPgxgzkGiL9UoAxdmE94MPVC9bBa9qnT/8dMR24GbKTETAOD1Tpzf0EScsmITqBAHA="
  file:
    - "linux-x64.zip"
    - "macos-x64.zip"
    - "windows-x64.zip"
  skip_cleanup: true
  all_branches: true  # https://github.com/travis-ci/travis-ci/issues/1675
  on:
    tags: true
